version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.20.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-
      - run:
          name: Install dependencies with legacy peer deps
          command: npm install --legacy-peer-deps
      - save_cache:
          paths:
            - ~/.npm
          key: npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Run tests
          command: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
