version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.20.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-
      - run:
          name: Install dependencies with legacy peer deps
          command: npm install --legacy-peer-deps
      - save_cache:
          paths:
            - ~/.npm
          key: npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Add a default test script to package.json
          command: |
            jq '.scripts.test = "jest"' package.json > package.tmp.json && mv package.tmp.json package.json
      - run:
          name: Install Jest
          command: npm install --save-dev jest
      - run:
          name: Run tests with Jest
          command: npm test || echo "No tests found, skipping."
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
